### PR TITLE
initial APIClient class

### PR DESCRIPTION
**Pull request by jsirish**
allows API keys to be set via config

### CODE REVIEW

**Comment by jsirish** [comment]
fixes #2

**Comment by muskie9** [comment]
Cloning this via git... need to get the composer file sured up w/the name noted in the readme for composer management with vcs declaration for the time being.

**Comment by muskie9** [comment]
I just saw the other PR for the composer update... merged so just need a rebase for composer usage.

**Comment by muskie9** [comment]
I did a rebase and force push so this should now have your initial work as well as adjustments I made for the SSO stuff.

**Review by muskie9 — APPROVED** [review]

**Pull request merged**
